---
- hosts: all
  gather_facts: false
#  ignore_errors: true
  tasks:
       - name: check the date
         command: date
         ignore_errors: yes
       - name: check uptime
         command: |
                uptime
                nproc
                date